# Exploratory Data Analysis

In [66]:
import pandas as pd
import numpy as np 
from plotly.subplots import make_subplots
import plotly.graph_objects as go
df = pd.read_csv('air.csv')

# get months and day of the week
df['Month'] = df.Date.map(lambda x: int(x.split('/')[1]))
df['Season'] = (df.Month % 12)//3
df['Time'] = (df.Time.map(lambda x: x.split(':')[0]).astype(int)/24)*2*np.pi
# df['cos(t)'] = df.Time.map(np.cos)
# df['sin(t)'] = df.Time.map(np.sin)

# split target and features 
targets = df['T']
inputs = df.drop(['T', 'Date', 'Time'], axis=1)
inputs

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,Month,Season
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,48.9,0.7578,3,1
1,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,47.7,0.7255,3,1
2,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,54.0,0.7502,3,1
3,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,60.0,0.7867,3,1
4,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,59.6,0.7888,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,3.1,1314.0,-200.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,29.3,0.7568,4,1
9353,2.4,1163.0,-200.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,23.7,0.7119,4,1
9354,2.4,1142.0,-200.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,18.3,0.6406,4,1
9355,2.1,1003.0,-200.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,13.5,0.5139,4,1
9356,2.2,1071.0,-200.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,13.1,0.5028,4,1

## Univariate Analysis

In [68]:
len(inputs.columns)

14

In [70]:
fig = make_subplots(rows=3, cols=5)
for col in inputs.columns:
    fig.add_trace(go.Histogram(inputs[col].values))

ValueError: The first argument to the plotly.graph_objs.Histogram
constructor must be a dict or
an instance of :class:`plotly.graph_objs.Histogram`